export const noEmail = "未公开公司级邮箱（仅官方表单/公司页）";

export const companies = [
  {
    name: "Savvy Games Group / Scopely",
    country: "Saudi Arabia / US",
    region: "Saudi / GCC",
    website: "https://www.savvygames.com/",
    type: "PIF 支持的全球游戏控股/收购平台；Scopely 为旗下移动发行实体",
    works: "MONOPOLY GO!, Stumble Guys, Star Trek Fleet Command, Pokemon GO/Niantic games",
    scale: "Savvy 2023 年以 49 亿美元收购 Scopely；Scopely 2025 年完成 Niantic 游戏业务 35 亿美元收购。",
    signal: "最强投资/收购信号；可谈项目/团队收购、战略投资或并入 Scopely mobile live-game 体系。",
    scores: [30, 25, 20, 15, 9],
    deals: "acq_asset; investment; publishing_mg",
    dealText: "战略投资；项目/团队收购；Savvy/Scopely 发行或并入讨论",
    entry: "Savvy corporate development / strategic investments；Scopely partnerships；CEO office 暖介绍",
    contactUrl: "https://www.savvygames.com/contact",
    email: noEmail,
    emailNote: "官网仅公开联系表单；建议表单 + LinkedIn + 共同投资人/顾问引荐。",
    angle: "包装为 US-tested mobile casual adventure/simulation asset，可补 Scopely 的 casual/social live game portfolio。",
    next: "A1 首轮。准备 1 页 teaser、2 分钟 gameplay、KPI 区间和可选交易结构。",
    confidence: "High",
    sources: [
      "https://www.savvygames.com/",
      "https://www.savvygames.com/news/savvy-games-group-completes-acquisition-of-scopely",
      "https://www.scopely.com/en/news/scopely-to-acquire-niantic-games-business-which-includes-pokemon-go-one-of-the-most-successful-mobile-games-of-all-time"
    ]
  },
  {
    name: "Playtika",
    country: "Israel",
    region: "Israel",
    website: "https://www.playtika.com/",
    type: "上市移动游戏集团；活跃收购方",
    works: "Slotomania, Bingo Blitz, June's Journey/Wooga, Best Fiends/Seriously, Dice Dreams/SuperPlay",
    scale: "上市公司；约 3,000+ 人；2024 年宣布收购 SuperPlay，2025 年仍预留 bolt-on M&A 预算。",
    signal: "长期通过收购补充移动游戏组合，Wooga/Seriously/SuperPlay 与休闲冒险和社交玩法用户相邻。",
    scores: [30, 24, 19, 15, 8],
    deals: "acq_asset; investment; publishing_mg",
    dealText: "项目/团队收购；战略投资；发行/LiveOps 合作",
    entry: "Corporate Development；M&A；Wooga / SuperPlay / Seriously 相关业务线",
    contactUrl: "https://www.playtika.com/",
    email: "ir@playtika.com",
    emailNote: "Playtika IR 官方页面公开 ir@playtika.com；用于请求转 corporate development / BD。",
    angle: "把 Family Island-like 的冒险、建造、长线活动与 Wooga/SuperPlay 的休闲长线运营能力连接。",
    next: "A1 首轮。邮件主诉求放收购/战略投资，发行作为备选结构。",
    confidence: "High",
    sources: [
      "https://www.playtika.com/",
      "https://investors.playtika.com/",
      "https://investors.playtika.com/news-releases/news-release-details/playtika-enters-agreement-acquire-superplay-creator-hit-mobile/"
    ]
  },
  {
    name: "Sandsoft Games / Stellar Gate",
    country: "Saudi Arabia",
    region: "Saudi / GCC",
    website: "https://sandsoft.com/",
    type: "Saudi mobile-first developer, publisher and investor；NetEase JV 覆盖 MENA 发行",
    works: "Sandsoft publishing portfolio, Stellar Gate JV, DC Heroes & Villains regional publishing signal",
    scale: "Riyadh HQ，另有 Barcelona、Helsinki、Shanghai；官方提供 UA、发行、投资、测试、共研和本地化支持。",
    signal: "区域发行最贴；官方写明欢迎已有 early promising metrics 的 hybrid casual mobile games 提交。",
    scores: [24, 25, 20, 15, 9],
    deals: "publishing_mg; investment; co-development",
    dealText: "MENA/全球发行；战略投资；UA funding；共研/LiveOps",
    entry: "Publishing team；Investment / funding support；Stellar Gate route",
    contactUrl: "https://sandsoft.com/publishing/",
    email: "pr@sandsoft.com",
    emailNote: "官网 contact 页面公开 pr@sandsoft.com；BD 仍优先 publishing 表单和 LinkedIn 暖介绍。",
    angle: "直接引用其筛选语境：mature/已上线、mobile-first、hybrid/casual、已有 promising KPI。",
    next: "A1 首轮。先走 publishing 表单，标题写 US-tested metrics + MENA scaling + flexible structure。",
    confidence: "High",
    sources: [
      "https://sandsoft.com/publishing/",
      "https://sandsoft.com/contact-us/",
      "https://ir.netease.com/node/14396"
    ]
  },
  {
    name: "Moon Active",
    country: "Israel",
    region: "Israel",
    website: "https://www.moonactive.com/",
    type: "大型移动休闲/社交游戏公司；Family Island 所属集团",
    works: "Coin Master, Family Island, Travel Town",
    scale: "约 1,000+ 人；具备极强 UA、economy、LiveOps 能力。",
    signal: "产品相似度最高但竞争敏感；适合高层/暖介绍探索资产并购或团队吸收。",
    scores: [22, 25, 20, 15, 6],
    deals: "acq_asset; investment",
    dealText: "资产/团队收购；战略合作；高层交流",
    entry: "Founder/CEO office；Corporate / strategy；共同投资人暖介绍",
    contactUrl: "https://www.moonactive.com/",
    email: noEmail,
    emailNote: "未找到公开公司级邮箱；竞争敏感目标建议只用暖介绍或顾问路线。",
    angle: "强调不是 clone，而是 US-tested adjacent simulation/adventure loop，可作为品类/团队/技术资产讨论。",
    next: "A1 但只走暖介绍。NDA 前只给极简 teaser，不发 build 和精确 cohort。",
    confidence: "High",
    sources: [
      "https://www.moonactive.com/",
      "https://www.pocketgamer.biz/industry/moon-active/",
      "https://mobilegamer.biz/coin-master-maker-moon-active-set-to-add-two-more-soft-launches/"
    ]
  },
  {
    name: "Yalla Group / Yalla Game",
    country: "United Arab Emirates",
    region: "UAE / Gulf",
    website: "https://www.yalla.com/",
    type: "NYSE 上市 MENA social networking and gaming company",
    works: "Yalla Ludo, Yalla Baloot, 101 Okey Yalla, YallaChat, WeMuslim",
    scale: "NYSE:YALA；公开称为 MENA-based online social networking and gaming company。",
    signal: "区域玩家、社交游戏、支付和社群能力强；可谈投资、发行或资产合作。",
    scores: [20, 22, 19, 15, 8],
    deals: "investment; publishing_mg; acq_asset",
    dealText: "战略投资；区域发行/运营；资产合作；社交化增长合作",
    entry: "Investor Relations；Yalla Game leadership；corporate strategy",
    contactUrl: "https://ir.yalla.com/IR-Contacts",
    email: "ir@yalla.com",
    emailNote: "IR 官方页面公开 ir@yalla.com；商务机会建议请求转 Yalla Game / corporate strategy。",
    angle: "把项目讲成可进入其 MENA social gaming ecosystem 的长线休闲冒险/经营产品。",
    next: "A1/A2。先发 IR/strategy 版 teaser，询问是否可转到游戏业务负责人。",
    confidence: "High",
    sources: [
      "https://ir.yalla.com/Investor-FAQs",
      "https://ir.yalla.com/IR-Contacts",
      "https://www.pocketgamer.biz/the-top-30-mena-game-makers-of-2025/"
    ]
  },
  {
    name: "Tamatem Games / Tamatem Plus",
    country: "Jordan / UAE / Saudi Arabia",
    region: "Jordan / Levant",
    website: "https://tamatem.co/",
    type: "Arabic-speaking MENA mobile publisher；发行、本地化、支付与分发平台",
    works: "VIP Baloot, Land of Heroes, Revenge of the Brave, Tamatem Plus",
    scale: "官方称 50+ released titles、100M+ downloads、1M MAU；JordanICT 口径 150M+ downloads。",
    signal: "区域发行最直接：Arabic localization、UA、distribution、monetization、community、whale management。",
    scores: [18, 25, 19, 15, 9],
    deals: "publishing_mg; investment",
    dealText: "MENA 发行；本地化与支付；UA/LiveOps；少数投资或收入分成",
    entry: "Publishing / Tamatem Plus；CEO office；Business Development",
    contactUrl: "https://tamatem.co/",
    email: noEmail,
    emailNote: "官网 footer 和第三方目录有 mailto 但当前页面显示脱敏；优先官网/LinkedIn/提交入口。",
    angle: "突出 US-tested metrics + Arabic market localization/payment potential。",
    next: "A1/A2。准备 MENA 发行版 teaser：KPI 区间、Arabic localization readiness、支付/LiveOps 需求。",
    confidence: "High",
    sources: [
      "https://tamatem.co/about-us/",
      "https://www.linkedin.com/company/tamatem-inc-",
      "https://jordanict.com/2023/company-profile/tamatem-games"
    ]
  },
  {
    name: "CrazyLabs / DECA / Embracer route",
    country: "Israel / Germany / Sweden",
    region: "Israel",
    website: "https://www.crazylabs.com/",
    type: "DECA/Embracer 体系内 mobile casual publisher",
    works: "Super Stylist, Phone Case DIY, Tie Dye, casual/hypercasual portfolio",
    scale: "大型 mobile casual publisher；Embracer 官方公告收购 CrazyLabs，DECA 负责 live games 运营。",
    signal: "发行适配高，集团路线可能支持资产或团队讨论；需验证 Embracer 重组后的审批口径。",
    scores: [20, 24, 20, 14, 8],
    deals: "publishing_mg; acq_asset; co-development",
    dealText: "发行/UA 测试；LiveOps 托管；资产/团队并入；共研",
    entry: "CrazyLabs publishing；DECA partner route；Embracer group route",
    contactUrl: "https://www.crazylabs.com/publishing/",
    email: "support@crazylabs.com",
    emailNote: "官网公开 support@；发行提案仍优先 publisher form。",
    angle: "用 CPI/留存区间说明项目已过概念阶段，问是否适合二次测试、发行或 DECA 托管/并购路径。",
    next: "A2。分 CrazyLabs 和 DECA 两条线写，不只发集团总入口。",
    confidence: "High",
    sources: [
      "https://www.crazylabs.com/",
      "https://www.crazylabs.com/publishing/",
      "https://www.embracer.com/releases/embracer-enters-into-an-agreement-to-acquire-crazylabs/"
    ]
  },
  {
    name: "Merak Gaming Fund / Merak Capital",
    country: "Saudi Arabia",
    region: "Regional investor",
    website: "https://merak.capital/",
    type: "Saudi gaming fund；Seed-Series B；Exel Gaming Accelerator",
    works: "Merak Gaming Fund, Exel Gaming Accelerator；Fahy/Starvania/Sheba Joy 投资信号",
    scale: "官网称 Merak Gaming Fund 为 8000 万美元，支持 game development、publishing、gaming technology startups。",
    signal: "融资线强；可作为桥接/战略融资和 Saudi ecosystem route。",
    scores: [24, 18, 14, 15, 10],
    deals: "investment",
    dealText: "股权投资；桥接融资；Saudi setup/accelerator；后续发行介绍",
    entry: "Merak Gaming Fund application；investment team",
    contactUrl: "https://merak.capital/contact",
    email: "gaming@merak.capital; contact@merak.capital",
    emailNote: "Merak Gaming Fund 搜索摘录公开 gaming@merak.capital；官网 contact 页面公开 contact@merak.capital。",
    angle: "投资人版叙事：US test validation、现金缺口、下一轮里程碑、Saudi/MENA publishing option。",
    next: "A1 并行融资线。准备投资人版 KPI teaser 和 12 个月资金计划。",
    confidence: "High",
    sources: [
      "https://merak.capital/about",
      "https://merak.capital/venture-capital/",
      "https://merak.capital/contact"
    ]
  },
  {
    name: "Impact46 Gaming Fund",
    country: "Saudi Arabia",
    region: "Regional investor",
    website: "https://impact46.sa/",
    type: "Saudi CMA-licensed asset manager；SAR 150M gaming fund",
    works: "Fahy, Starvania, Spoilz, Spekter, NJD, Game Cooks, Alpaka, Hypemasters portfolio signals",
    scale: "官网称 i46 Gaming Fund 为 SAR 150M，公开寻找 Saudi gaming founders；有多笔游戏工作室投资新闻。",
    signal: "游戏专项投资线强，且与 Sandsoft/Savvy 生态可形成转介绍价值。",
    scores: [24, 18, 14, 15, 10],
    deals: "investment",
    dealText: "股权投资；桥接融资；Saudi/MENA 生态转介绍",
    entry: "i46 Gaming Fund submission；investment team",
    contactUrl: "https://impact46.sa/i46-gaming-fund/",
    email: "info@impact46.sa",
    emailNote: "Impact46 Gaming Fund 页面公开 info@impact46.sa。",
    angle: "强调美国测试验证和下一阶段可通过 Saudi/MENA capital + publisher network 降低资金断点风险。",
    next: "A1 并行融资线。邮件要更像融资 teaser，不要只谈发行。",
    confidence: "High",
    sources: [
      "https://impact46.sa/i46-gaming-fund/",
      "https://www.pocketgamer.biz/impact46-invests-67m-in-five-saudi-game-studios/",
      "https://thestartupscene.me/INVESTMENTS/Saudi-VC-Impact46-Invests-Over-6-6-Million-in-Five-Gaming-Studios"
    ]
  },
  {
    name: "Dream Games",
    country: "Turkey",
    region: "Turkey",
    website: "https://dreamgames.com/",
    type: "大型移动休闲游戏公司",
    works: "Royal Match, Royal Kingdom",
    scale: "土耳其头部 mobile casual 公司；Royal Match / Royal Kingdom 驱动全球休闲产品能力。",
    signal: "休闲用户、广告投放和长线运营模型高度相关；独立收购/外部发行意愿需高层验证。",
    scores: [17, 24, 20, 14, 7],
    deals: "investment; acq_asset; co-development",
    dealText: "战略投资；资产/团队讨论；共研；高层交流",
    entry: "Founder/leadership；strategy / product leadership",
    contactUrl: "https://dreamgames.com/",
    email: "info@dreamgames.com",
    emailNote: "官网公开 info@dreamgames.com；建议请求转 strategy/corp dev。",
    angle: "定位为与 Royal Match 不同但面向 casual female/cozy audience 的 validated simulation-adventure loop。",
    next: "A2。高层短邮件优先，不要长篇 pitch。",
    confidence: "High",
    sources: [
      "https://dreamgames.com/",
      "https://dreamgames.com/games/",
      "https://www.linkedin.com/company/dream-games/"
    ]
  },
  {
    name: "Jawaker / Stillfront Group",
    country: "United Arab Emirates / Sweden",
    region: "UAE / Gulf",
    website: "https://www.jawakergames.com/",
    type: "Stillfront 旗下 MENA social/card/board gaming platform",
    works: "Jawaker",
    scale: "Stillfront 2021 年以 2.05 亿美元 upfront 收购 Jawaker；MENA 经典 PvP 桌牌/卡牌平台。",
    signal: "MENA 玩家、支付渠道、社交长线运营能力强；买方路径多半走 Stillfront group M&A。",
    scores: [20, 21, 17, 14, 7],
    deals: "acq_asset; investment; publishing_mg",
    dealText: "Stillfront 路线收购/投资；MENA 发行/社交运营；区域合作",
    entry: "Jawaker leadership；Stillfront group M&A / IR",
    contactUrl: "https://www.jawakergames.com/",
    email: noEmail,
    emailNote: "未找到公开公司级 BD 邮箱；建议 Jawaker LinkedIn + Stillfront IR/集团路线。",
    angle: "若项目有社交、家族、公会、活动循环，强调 Jawaker MENA social graph 与 Stillfront global UA。",
    next: "A2。先问 Stillfront/Jawaker 是否评估 mobile casual/simulation assets。",
    confidence: "High",
    sources: [
      "https://www.jawakergames.com/",
      "https://www.stillfront.com/en/stillfront-group-acquires-jawaker-and-continues-expansion-in-the-mena-region-and-intends-to-raise-new-financing/",
      "https://www.pocketgamer.biz/the-top-30-mena-game-makers-of-2025/"
    ]
  },
  {
    name: "Playhera",
    country: "Saudi Arabia",
    region: "Saudi / GCC",
    website: "https://playhera.com/",
    type: "MENA publishing, creator-led live events and esports/gaming platform",
    works: "PLAYHERA MENA platform, publisher services, Playhera Academy",
    scale: "官方称 Premier Publisher for MENA，提供本地化、创作者、支付、资金支持和区域扩张。",
    signal: "MENA 发行和创作者增长强相关；资金/投资口径弱于 Sandsoft/Savvy。",
    scores: [15, 24, 18, 14, 8],
    deals: "publishing_mg; investment",
    dealText: "MENA 发行；创作者/赛事营销；本地支付；资金支持",
    entry: "Publish with Playhera；publisher team",
    contactUrl: "https://playhera.com/",
    email: noEmail,
    emailNote: "官方页面摘要显示可直接 reach out，但邮箱在检索结果中被脱敏；优先 Submit a Game。",
    angle: "强调 MENA 玩家付费、本地化和 creator-led LiveOps，询问是否能做区域验证或 funding-supported launch。",
    next: "A2。提交游戏前先发简短 deck，说明美国数据和 MENA 假设。",
    confidence: "Medium",
    sources: [
      "https://playhera.com/",
      "https://business.playhera.com/our-services/",
      "https://www.zawya.com/en/press-release/playhera-mena-unveiled-in-a-multi-million-dollar-deal-with-zain-tzi92axp"
    ]
  },
  {
    name: "Lobah / Lobah Play",
    country: "Saudi Arabia",
    region: "Saudi / GCC",
    website: "https://lobah.com/",
    type: "Saudi game company and social game publishing/platform route",
    works: "Samla, Jackaroo Strike, Kingdom of Letter, Habhab, Lobah Play, Kix",
    scale: "官方称 2024 年成立；PocketGamer 报道其获得 1200 万美元资金支持。",
    signal: "Saudi local/global ambition 明确；Lobah Play 有社交游戏平台/发行接入价值。",
    scores: [18, 22, 17, 14, 8],
    deals: "publishing_mg; investment; co-development",
    dealText: "Saudi/MENA 平台发行；投资/共研；社交增长合作",
    entry: "Lobah Play developer/business team；company leadership",
    contactUrl: "https://www.lobah.com/contact",
    email: noEmail,
    emailNote: "官网提供联系表单；未找到可读公司级邮箱。",
    angle: "若项目愿意做 Saudi/MENA platform integration，可把 Lobah Play 作为本地增长/发行试验线。",
    next: "A2/B1。先问平台发行/合作，不要一开始只谈收购。",
    confidence: "Medium",
    sources: [
      "https://lobah.com/",
      "https://www.lobah.com/contact",
      "https://www.pocketgamer.biz/lobah-on-raising-12m-and-the-opportunity-for-culturalised-games-in-mena/"
    ]
  },
  {
    name: "Babil Games / Stillfront Group",
    country: "UAE / Jordan / Sweden",
    region: "Jordan / Levant",
    website: "https://babilgames.com/",
    type: "Stillfront 旗下 MENA mobile strategy publisher",
    works: "Nida Harb 3, The Grand Frontier, Strike of Nations",
    scale: "Stillfront 收购 Babil；官网强调 MENA 市场发行、本地化、UA 和合作伙伴网络。",
    signal: "MENA 发行、本地化和长线 SLG 运营能力强；休闲模拟需解释用户和经济系统相邻性。",
    scores: [18, 22, 18, 13, 7],
    deals: "publishing_mg; acq_asset; co-development",
    dealText: "MENA 发行；Stillfront 路线资产/团队交易；本地化/LiveOps",
    entry: "Babil services/publishing；Stillfront M&A/IR",
    contactUrl: "https://babilgames.com/",
    email: noEmail,
    emailNote: "官网以 contact form 为主；未找到公开公司级 BD 邮箱。",
    angle: "从 MENA market impact 和 long-term live game operation 切入，询问是否看休闲冒险/经营品类扩张。",
    next: "A2/B1。适合作为 Stillfront MENA 路线，与 Jawaker 并行。",
    confidence: "High",
    sources: [
      "https://babilgames.com/",
      "https://www.stillfront.com/en/stillfront-group-ab-stillfront-completes-the-acquisition-of-babil-games-2/",
      "https://www.stillfront.com/en/stillfront-group-ab-stillfront-forvarvar-babil-games-den-ledande-mobilspelsforlaggaren-i-mena-regionen/"
    ]
  },
  {
    name: "Rollic / Zynga / Take-Two",
    country: "Turkey / US",
    region: "Turkey",
    website: "https://www.rollicgames.com/",
    type: "Zynga/Take-Two 旗下 hyper/hybrid casual publisher",
    works: "Blob Runner 3D, High Heels!, Tangle Master, hyper/hybrid casual portfolio",
    scale: "Zynga 旗下土耳其 mobile publisher；公开 publish-with-us 入口清晰。",
    signal: "发行适配高；独立收购/投资需要走 Zynga/Take-Two corporate route。",
    scores: [16, 22, 20, 12, 8],
    deals: "publishing_mg; acq_asset",
    dealText: "发行/测试；Zynga route 资产/团队讨论；UA 放大",
    entry: "Publish with Rollic；Zynga corporate / publishing route",
    contactUrl: "https://www.rollicgames.com/publish-with-us",
    email: "support@rollicgames.com",
    emailNote: "公开支持邮箱仅 fallback；发行/合作优先 publish-with-us 表单。",
    angle: "用美国 CPI/留存直接判断是否可进入二次测试/发行 pipeline。",
    next: "A2/B1。发行版模板优先，投资/收购只放在末尾。",
    confidence: "High",
    sources: [
      "https://www.rollicgames.com/",
      "https://www.rollicgames.com/publish-with-us",
      "https://www.zynga.com/"
    ]
  },
  {
    name: "YallaPlay",
    country: "United Arab Emirates",
    region: "UAE / Gulf",
    website: "https://www.yallaplay.com/mobile",
    type: "mobile card/PvP studio；AI-backed live operations",
    works: "Spades Masters, Tarneeb Masters, Gin Rummy Masters, Zombie World",
    scale: "官方称 Spades Masters 由 Miniclip 发行并有数百万下载；页面显示 310k+ games/day。",
    signal: "实时 PvP、社交、长期生命周期能力相关；适合合作/技术/区域发行或小规模投资讨论。",
    scores: [15, 20, 18, 13, 7],
    deals: "co-development; publishing_mg; investment",
    dealText: "共研；区域发行/运营；少数投资；技术/后端合作",
    entry: "Leadership / business development",
    contactUrl: "https://www.yallaplay.com/mobile",
    email: noEmail,
    emailNote: "官网显示 reach us 邮箱但当前检索结果脱敏；优先官网/LinkedIn。",
    angle: "如果项目社交系统较强，可强调 AI/real-time/PvP/liveops 能力与长线 retention 的协同。",
    next: "B1。先谈合作和区域运营，收购放弱。",
    confidence: "Medium",
    sources: [
      "https://www.yallaplay.com/mobile",
      "https://www.isakaba.com/yallaplay/",
      "https://www.pocketgamer.biz/the-top-30-mena-game-makers-of-2025/"
    ]
  },
  {
    name: "FunVent Studios",
    country: "United Arab Emirates",
    region: "UAE / Gulf",
    website: "https://funvent.cc/",
    type: "Dubai-based casual puzzle mobile developer/publisher",
    works: "Tiledom, 2 Tiles, Tile Park, Zoo Puzzle, Connect Animal",
    scale: "官网称 400M+ players、27M+ MAU、5M+ DAU；PocketGamer 2025 MENA Top 30 收录。",
    signal: "移动休闲、puzzle、UA 和全球发行相关；收购能力未知，但可作为区域/全球休闲买方补充。",
    scores: [12, 23, 18, 13, 9],
    deals: "publishing_mg; investment; co-development",
    dealText: "发行/合作；少数投资；共研；产品/UA 交流",
    entry: "Business development；founder/leadership",
    contactUrl: "https://funvent.cc/",
    email: "hello@funvent.cc",
    emailNote: "官网公开 hello@funvent.cc。",
    angle: "强调休闲女性/家庭用户、低 CPI 和长线内容潜力，请对方判断是否有 portfolio gap。",
    next: "B1。邮件要短，先问是否评估 external casual simulation titles。",
    confidence: "High",
    sources: [
      "https://funvent.cc/",
      "https://www.pocketgamer.biz/the-top-30-mena-game-makers-of-2025/",
      "https://www.linkedin.com/company/funvent-studios/"
    ]
  },
  {
    name: "ONEMT Middle East",
    country: "United Arab Emirates / China",
    region: "UAE / Gulf",
    website: "https://www.onemt.com/",
    type: "Dubai-headquartered global mobile game developer/distributor",
    works: "Revenge of Sultans, Rise of the Kings, War Eternal, Days of Empire",
    scale: "LinkedIn 口径 501-1,000 人；官方称 18 language versions，多款产品位列多国榜单。",
    signal: "MENA/Arabic SLG 发行经验强；Family Island-like 需从建造/经营/中长期 progression 角度解释。",
    scores: [12, 21, 18, 13, 8],
    deals: "publishing_mg; co-development; investment",
    dealText: "MENA/全球发行；共研；轻量投资；本地化运营",
    entry: "Business cooperation；Dubai office；publishing/distribution",
    contactUrl: "https://pte.onemt.com/contact",
    email: "business@onemt.com",
    emailNote: "ONEMT contact 页面公开 business@onemt.com。",
    angle: "如果要找熟悉 Arab market 的 SLG/策略发行团队，ONEMT 可作为区域运营经验参照。",
    next: "B1。突出产品经济系统与区域本地化，而非单纯 cozy/farming。",
    confidence: "High",
    sources: [
      "https://www.onemt.com/",
      "https://pte.onemt.com/contact",
      "https://www.linkedin.com/company/onemt"
    ]
  },
  {
    name: "Steer Studios",
    country: "Saudi Arabia",
    region: "Saudi / GCC",
    website: "https://www.steerstudios.com/",
    type: "Savvy Games Group 旗下 Riyadh game studio",
    works: "Grunt Rush, Tom and Jerry Blast signal",
    scale: "Savvy 官网称 Steer 为 Riyadh game development studio；IsaKaba 口径 80+ 人。",
    signal: "更像研发实体，不一定是外部发行/收购入口；可作为 Savvy 本地 studio 吸收/共研线索。",
    scores: [14, 18, 17, 14, 6],
    deals: "co-development; acq_asset; investment",
    dealText: "共研；团队吸收；Savvy 路线资产讨论",
    entry: "Steer leadership；Savvy corporate route",
    contactUrl: "https://www.steerstudios.com/",
    email: "customersupport@steerstudios.com",
    emailNote: "仅公开游戏客服邮箱，不建议作为 BD 主入口；优先 Savvy/Steer LinkedIn 暖介绍。",
    angle: "把团队和产品产能作为 Savvy 本地研发生态可吸收的 external project/team。",
    next: "B1。若 Savvy 主线无响应，再用 Steer 作为侧门验证。",
    confidence: "Medium",
    sources: [
      "https://www.steerstudios.com/",
      "https://www.savvygames.com/",
      "https://www.isakaba.com/steer-studios/"
    ]
  },
  {
    name: "Ace Games",
    country: "Turkey",
    region: "Turkey",
    website: "https://ace.games/",
    type: "成长型 mobile casual studio",
    works: "Fiona's Farm, casual puzzle/adventure portfolio",
    scale: "土耳其 casual mobile studio；产品与轻冒险/农场/建造品类相邻。",
    signal: "品类相邻度高，但独立买方能力不如 Playtika/Moon/Dream。",
    scores: [12, 22, 17, 13, 6],
    deals: "investment; co-development; acq_asset",
    dealText: "战略合作；轻量投资；团队/资产讨论；产品/UA 交流",
    entry: "Leadership；product / strategy",
    contactUrl: "https://ace.games/",
    email: noEmail,
    emailNote: "未找到公开公司级邮箱；使用官网/LinkedIn。",
    angle: "强调 Fiona's Farm 相邻品类经验，问是否关注已验证 US metrics 的 external simulation-adventure team。",
    next: "B1。推荐 LinkedIn 定向创始人/产品负责人。",
    confidence: "Medium",
    sources: [
      "https://ace.games/",
      "https://ace.games/",
      "https://www.linkedin.com/company/ace-games/"
    ]
  },
  {
    name: "Gram Games / Zynga",
    country: "Turkey / US",
    region: "Turkey",
    website: "https://www.gram.gs/",
    type: "Zynga/Take-Two 旗下 mobile casual/merge studio",
    works: "Merge Dragons!, 1010!, Merge Magic!",
    scale: "Zynga/Take-Two 旗下；Merge Dragons! 等休闲/merge 产品线。",
    signal: "与 Family Island-like 的 merge、建造、休闲用户相邻；独立买方能力有限。",
    scores: [14, 22, 18, 12, 6],
    deals: "acq_asset; co-development; publishing_mg",
    dealText: "Zynga 路线资产/团队讨论；共研；发行/运营合作",
    entry: "Gram leadership；Zynga corporate / publishing",
    contactUrl: "https://www.gram.gs/",
    email: noEmail,
    emailNote: "未找到公开公司级邮箱；建议走 Zynga/Take-Two 或 LinkedIn。",
    angle: "从 merge/建造系统和长线内容生产能力切入。",
    next: "B1。作为 Zynga 土耳其 studio map 的一部分触达。",
    confidence: "High",
    sources: [
      "https://www.gram.gs/",
      "https://www.zynga.com/",
      "https://www.linkedin.com/company/gram-games/"
    ]
  },
  {
    name: "SuperPlay / Playtika",
    country: "Israel",
    region: "Israel",
    website: "https://www.superplay.co/",
    type: "Playtika acquired mobile casual studio",
    works: "Dice Dreams, Domino Dreams",
    scale: "Playtika 2024 年宣布以 7 亿美元 upfront + 最高 12.5 亿美元 earnout 收购 SuperPlay。",
    signal: "coin-looter/board/social casual 与休闲冒险用户相邻；更适合作为 Playtika 路线业务线补充。",
    scores: [16, 21, 18, 13, 6],
    deals: "acq_asset; investment; co-development",
    dealText: "Playtika 路线资产/团队讨论；共研；产品经验交流",
    entry: "Playtika corporate；SuperPlay leadership via warm intro",
    contactUrl: "https://www.playtika.com/",
    email: "ir@playtika.com",
    emailNote: "建议通过 Playtika IR 请求转 corp dev/BD，不单独冷发 SuperPlay。",
    angle: "把项目与 Dice Dreams/Domino Dreams 的社交休闲、活动、内容消耗节奏做对照。",
    next: "B1。若 Playtika 主线回应，再要求转 SuperPlay/产品评审。",
    confidence: "High",
    sources: [
      "https://investors.playtika.com/news-releases/news-release-details/playtika-enters-agreement-acquire-superplay-creator-hit-mobile/",
      "https://www.playtika.com/",
      "https://www.superplay.co/"
    ]
  },
  {
    name: "Good Job Games",
    country: "Turkey",
    region: "Turkey",
    website: "https://goodjobgames.com/",
    type: "mobile casual studio",
    works: "Color Bump 3D, Fun Race 3D, hyper/casual portfolio",
    scale: "土耳其移动休闲公司，有全球下载和快速迭代经验。",
    signal: "移动 casual 相关，收购/投资能力需验证；适合作为产品反馈和轻量合作线。",
    scores: [12, 21, 18, 12, 6],
    deals: "investment; co-development; publishing_mg",
    dealText: "战略合作；轻量投资；共研；发行测试",
    entry: "Leadership；business / publishing",
    contactUrl: "https://goodjobgames.com/",
    email: noEmail,
    emailNote: "未找到公开公司级邮箱；使用官方联系入口。",
    angle: "用低 CPI/留存和 creative learning 说服其做快速产品评估。",
    next: "B1/B2。短邮件，不要把收购放在第一句。",
    confidence: "Medium",
    sources: [
      "https://goodjobgames.com/",
      "https://goodjobgames.com/games",
      "https://www.linkedin.com/company/good-job-games/"
    ]
  },
  {
    name: "Fahy Studios",
    country: "Saudi Arabia",
    region: "Saudi / GCC",
    website: "https://www.fahy.gg/",
    type: "Saudi hybrid-casual studio；向 publishing 发展",
    works: "Smash & Dash, Town Hero, Heist Party, RAWR signal",
    scale: "官网显示 Kwalee publishing partnership、Impact46/Merak strategic investment；新闻称 175 万美元融资。",
    signal: "资金/买方能力有限，但 Saudi hybrid-casual 网络价值高，适合作为合作、引荐和本地资金线索。",
    scores: [14, 19, 15, 13, 8],
    deals: "co-development; investment; publishing_mg",
    dealText: "共研；区域合作；投资人转介；轻量发行",
    entry: "Founder/leadership；Impact46/Merak route",
    contactUrl: "https://www.fahy.gg/",
    email: "info@fahy.gg",
    emailNote: "官网源码公开 info@fahy.gg；另有个人邮箱，不纳入主入口。",
    angle: "从 Saudi hybrid-casual ecosystem 和共同投资人网络切入，询问是否可互相转介或共研。",
    next: "B1。适合作为区域 networking，不作为首批收购对象。",
    confidence: "High",
    sources: [
      "https://www.fahy.gg/",
      "https://www.zawya.com/en/press-release/companies-news/fahy-secures-strategic-investment-of-175mln-from-impact46-and-merak-capital-hp5wv6xr",
      "https://impact46.sa/portfolio/fahy-studio/"
    ]
  },
  {
    name: "Boss Bunny Games / Waysun",
    country: "United Arab Emirates / US",
    region: "UAE / Gulf",
    website: "https://bossbunny.com/",
    type: "mobile games developer/publisher；Waysun MENAT publishing arm",
    works: "Freej partnership signal, casual/hypercasual mobile publishing",
    scale: "twofour54 公告称 Waysun 收购 Boss Bunny 多数股权，使其成为 MENAT publishing arm。",
    signal: "明确有区域发行和外资控股背景；当前活跃度需验证。",
    scores: [15, 19, 16, 13, 6],
    deals: "publishing_mg; investment; co-development",
    dealText: "MENAT 发行；投资/加速器；共研；本地 IP 合作",
    entry: "Boss Bunny leadership；Waysun route；AD Gaming/twofour54 network",
    contactUrl: "https://bossbunny.com/",
    email: noEmail,
    emailNote: "未找到公开公司级邮箱；建议通过官网/LinkedIn/twofour54。",
    angle: "强调其曾被定位为 MENAT publishing arm，询问是否仍看外部 mobile casual 项目。",
    next: "B1/B2。先确认当前是否活跃评估新项目。",
    confidence: "Medium",
    sources: [
      "https://www.twofour54.com/en/news-and-updates/press-releases/waysun-buys-majority-stake-in-abu-dhabi-start-up-boss-bunny/",
      "https://www.pocketgamer.biz/industry/boss-bunny-games/",
      "https://www.cbinsights.com/company/boss-bunny"
    ]
  },
  {
    name: "Candivore",
    country: "Israel",
    region: "Israel",
    website: "https://www.candivore.io/",
    type: "mobile casual/social game studio",
    works: "Match Masters",
    scale: "成长型 mobile casual studio；Match Masters 为高竞争社交 match-3 产品。",
    signal: "休闲/社交/竞技投放能力相关；买方能力不如 Playtika，但可作为战略合作或收购兴趣验证。",
    scores: [11, 21, 17, 12, 7],
    deals: "investment; co-development; acq_asset",
    dealText: "战略合作；少数投资；团队/资产讨论；产品交流",
    entry: "Leadership；business development",
    contactUrl: "https://www.candivore.io/",
    email: "contact@candivore.io",
    emailNote: "官网/terms 页面公开 contact@candivore.io。",
    angle: "强调休闲用户、社交竞争和活动经济，而非 farming 表层题材。",
    next: "B1/B2。先用短邮件问是否评估 adjacent casual titles。",
    confidence: "High",
    sources: [
      "https://www.candivore.io/",
      "https://www.matchmasters.io/",
      "https://www.linkedin.com/company/candivore/"
    ]
  },
  {
    name: "Spyke Games",
    country: "Turkey",
    region: "Turkey",
    website: "https://spyke.games/",
    type: "mobile casual studio",
    works: "Tile Busters, Blitz Busters",
    scale: "成长型土耳其 mobile casual studio；融资和产品能力较强。",
    signal: "品类/投放相关，可能更适合战略合作或融资交流。",
    scores: [13, 20, 17, 12, 6],
    deals: "investment; co-development; acq_asset",
    dealText: "战略合作；少数投资；产品/UA 交流；团队/资产讨论",
    entry: "Founder/leadership；product leadership",
    contactUrl: "https://spyke.games/",
    email: noEmail,
    emailNote: "未找到公开公司级邮箱；使用官网/LinkedIn。",
    angle: "用 US-tested casual metrics 切入，请对方判断品类相邻和团队协同。",
    next: "B1/B2。需要暖介绍提高回复率。",
    confidence: "Medium",
    sources: [
      "https://spyke.games/",
      "https://spyke.games/games/",
      "https://www.linkedin.com/company/spyke-games/"
    ]
  },
  {
    name: "Plarium / MTG",
    country: "Israel / Sweden",
    region: "Israel",
    website: "https://plarium.com/",
    type: "MTG 旗下 mobile/online game company",
    works: "RAID: Shadow Legends, Vikings: War of Clans",
    scale: "MTG 2024 年公告收购 Plarium；Plarium 为大型 F2P midcore/online studio。",
    signal: "F2P 运营和全球投放能力强，但品类偏 midcore；交易路线建议先走 MTG group。",
    scores: [15, 15, 19, 12, 7],
    deals: "acq_asset; investment; co-development",
    dealText: "MTG 路线投资/收购；运营/UA 合作；共研",
    entry: "MTG corporate；Plarium business contacts",
    contactUrl: "https://company.plarium.com/en/contacts/",
    email: "kyiv@plarium.com",
    emailNote: "Plarium contact 页面列为 Kyiv studio business inquiries；集团交易仍优先 MTG route。",
    angle: "如果项目经济系统/长期任务链强，可说明其与 F2P live operations 的相似性。",
    next: "B2。不要首轮只找 Plarium，先找 MTG 更合理。",
    confidence: "High",
    sources: [
      "https://company.plarium.com/en/contacts/",
      "https://www.mtg.com/plarium-acquisition-2024/",
      "https://www.mtg.com/gaming/"
    ]
  },
  {
    name: "UMX Studio",
    country: "Saudi Arabia",
    region: "Saudi / GCC",
    website: "https://umxstudio.co/",
    type: "Saudi mobile games studio",
    works: "King of Steering, Climbing Sand Dune, Drift X",
    scale: "PocketGamer 2025 MENA Top 30 称其 70M+ downloads、2M MAU；2024 年获得 Jetapult 投资。",
    signal: "区域玩家理解强，但品类偏 racing/drift；买方能力需验证。",
    scores: [12, 20, 16, 12, 6],
    deals: "co-development; investment; publishing_mg",
    dealText: "共研；区域合作；少数投资/转介；产品交流",
    entry: "Leadership；business development",
    contactUrl: "https://umxstudio.co/",
    email: noEmail,
    emailNote: "未找到公开公司级邮箱；使用官网 contact / LinkedIn。",
    angle: "如果想找 Saudi mobile hit-maker 的反馈，可用美国数据换取产品/市场判断。",
    next: "B2。低于 Sandsoft/Tamatem/Playhera 优先级。",
    confidence: "Medium",
    sources: [
      "https://umxstudio.co/",
      "https://www.pocketgamer.biz/the-top-30-mena-game-makers-of-2025/",
      "https://saudinow.co/storage/uploads/files/TfmRPetdZAe2fIBNxB0WiuCgXbZjOTcD40Lz2wxs.pdf"
    ]
  },
  {
    name: "Maysalward",
    country: "Jordan",
    region: "Jordan / Levant",
    website: "https://www.maysalward.com/",
    type: "MENA pioneer mobile game developer/publisher",
    works: "Dominoes Pro, Bounty Hunter, Puffout, Sheikh El Koba",
    scale: "2003 年成立；CrossBoundary 口径称 100+ original IPs、3.5M active user base。",
    signal: "区域洞察和本地化/发行经验强；资本能力有限，更适合作为合作/转介/区域运营顾问线。",
    scores: [12, 20, 16, 13, 8],
    deals: "publishing_mg; co-development; investment",
    dealText: "区域发行/运营；共研；轻量投资/转介；本地化合作",
    entry: "Business development；founder office",
    contactUrl: "https://www.maysalward.com/contact/",
    email: "info@maysalward.com",
    emailNote: "官网源码公开 info@maysalward.com；不使用个人邮箱作为主入口。",
    angle: "请其判断 MENA localization、content fit 和是否能引荐更有资金能力的区域买方。",
    next: "B2。作为生态转介绍目标很有价值。",
    confidence: "High",
    sources: [
      "https://www.maysalward.com/",
      "https://crossboundary.com/work/fundraising-mena-mobile-game-studio/",
      "https://www.isakaba.com/maysalward/"
    ]
  },
  {
    name: "Medrick",
    country: "UAE / Iran / Germany",
    region: "MENA publisher network",
    website: "https://medrickfze.com/",
    type: "MENA mobile/PC publisher and developer",
    works: "Summon Superheroes, Summon Ancient Heroes, mid-core/F2P portfolio",
    scale: "官网称 2008 年成立，15+ developed games、50+ published games，并有 Dubai 和 Berlin offices。",
    signal: "区域发行经验明确；资本/收购能力未知，适合 B-tier 发行/本地化备选。",
    scores: [10, 19, 16, 12, 8],
    deals: "publishing_mg; co-development",
    dealText: "MENA 发行；本地化/运营；共研",
    entry: "Publishing / business development",
    contactUrl: "https://medrickfze.com/",
    email: "info@medrickfze.com",
    emailNote: "官网公开 info@medrickfze.com。",
    angle: "用 MENA expansion/localization 需求切入，而非一开始谈收购。",
    next: "B2。先验证当前活跃游戏和发行能力。",
    confidence: "Medium",
    sources: [
      "https://medrickfze.com/",
      "https://www.linkedin.com/company/medrick/",
      "https://medrickfze.com/game-main-page/"
    ]
  },
  {
    name: "Game Power 7",
    country: "United Arab Emirates",
    region: "UAE / Gulf",
    website: "https://www.pocketgamer.biz/industry/game-power-7/",
    type: "Arabic online/mobile games publisher and developer",
    works: "Arabic Rappelz, Warriors' Line-Up, Sultans Mines, Cardia",
    scale: "官网称 2007 年成立、first Arabic company in publishing/localizing online games、22 countries、5 offices。",
    signal: "阿语 online/MMO/mobile 发行和本地化经验强；Family Island-like 适配中等。",
    scores: [10, 17, 16, 12, 8],
    deals: "publishing_mg; co-development",
    dealText: "MENA 发行；本地化；共研；区域渠道合作",
    entry: "Business development；marketing/publishing",
    contactUrl: "https://www.pocketgamer.biz/industry/game-power-7/",
    email: "business@gamepower7.com",
    emailNote: "Crunchbase/公开资料显示 business@gamepower7.com；官网页面有脱敏邮箱。",
    angle: "如果项目需要 Arabic online/game community 经验，可作为区域发行备选。",
    next: "B2。先问是否仍评估外部 mobile F2P。",
    confidence: "Medium",
    sources: [
      "https://www.pocketgamer.biz/industry/game-power-7/",
      "https://www.pocketgamer.biz/industry/game-power-7/",
      "https://www.crunchbase.com/organization/game-power-7"
    ]
  },
  {
    name: "Gamezop MENA",
    country: "Bahrain / India",
    region: "MENA publisher network",
    website: "https://www.gamezop.com/",
    type: "instant/casual games distribution platform；MENA regional office",
    works: "Gamezop instant games network, Quizzop, SkillClash",
    scale: "PocketGamer 2025 报道其投入 400 万美元拓展 Middle East，并将 Bahrain office 作为 MENA HQ。",
    signal: "不是传统发行商，但 casual distribution、广告变现和区域拓展相关。",
    scores: [12, 18, 15, 12, 7],
    deals: "publishing_mg; investment",
    dealText: "MENA 分发/渠道；广告变现合作；潜在小型收购/投资",
    entry: "Business development；MENA office",
    contactUrl: "https://www.gamezop.com/",
    email: noEmail,
    emailNote: "未找到公开公司级邮箱；使用官网/LinkedIn。",
    angle: "若需要快速低成本 MENA distribution 试水，可作为渠道线。",
    next: "B2。不是第一波融资/收购目标。",
    confidence: "Medium",
    sources: [
      "https://www.pocketgamer.biz/gamezop-commits-4m-to-expand-in-the-middle-east-with-a-new-office-in-bahrain/",
      "https://www.gamezop.com/",
      "https://www.linkedin.com/company/gamezop/"
    ]
  },
  {
    name: "Leango Studio",
    country: "Canada / MENA network",
    region: "MENA publisher network",
    website: "https://leangostudio.com/",
    type: "mobile game developer and MENA publisher",
    works: "Mafioso, Anna's Garden, Merge Legacy, Avangard, The Tasty City",
    scale: "官方 Publish 页面称以 MENA publisher 身份提供 monetization、本地化、营销、社区、QA 等服务。",
    signal: "Family Island-like 若包含 merge/mansion/cooking/casual economy，相邻度较高；资本能力未知。",
    scores: [9, 20, 15, 12, 7],
    deals: "publishing_mg; co-development",
    dealText: "MENA 发行；本地化/运营；共研",
    entry: "Publishing with Leango；business development",
    contactUrl: "https://leangostudio.com/publish/",
    email: noEmail,
    emailNote: "未找到公开公司级邮箱；使用官网 publish/contact。",
    angle: "强调 merge/casual/adventure 相邻点，请其判断 MENA 发行和本地化可行性。",
    next: "B2。适合作为中腰部区域发行备选。",
    confidence: "Medium",
    sources: [
      "https://leangostudio.com/publish/",
      "https://leangostudio.com/",
      "https://www.linkedin.com/company/leango-studio/"
    ]
  },
  {
    name: "Vplay Games",
    country: "MENA / Canada",
    region: "MENA publisher network",
    website: "https://vplaygames.com/",
    type: "cross-regional mobile game publisher focused on MENA",
    works: "Clash of Queens case study, Clash of Zombies case study, 100+ games powered signal",
    scale: "官网称 Game publisher in the Middle East，提供 art、marketing、localization、support、QA 和 submit your game form。",
    signal: "适合找 MENA publishing/localization/UA 反馈；资本或收购能力不明。",
    scores: [10, 19, 16, 12, 8],
    deals: "publishing_mg; co-development",
    dealText: "MENA/全球发行；本地化；QA/营销；共研",
    entry: "Submit your game；general inquiries",
    contactUrl: "https://vplaygames.com/contactus/",
    email: noEmail,
    emailNote: "官网 contact 页面显示 general inquiries 邮箱但当前结果脱敏；优先表单。",
    angle: "把项目作为已验证海外数据的 mobile title，让其判断 MENA publishing ROI。",
    next: "B2。先提交简版，不暴露精确 cohort。",
    confidence: "Medium",
    sources: [
      "https://vplaygames.com/",
      "https://vplaygames.com/contactus/",
      "https://ca.linkedin.com/company/vplaygames"
    ]
  },
  {
    name: "Bigger Games",
    country: "Turkey",
    region: "Turkey",
    website: "https://biggergames.com/",
    type: "mobile casual games studio",
    works: "Kitchen Masters, Design Masters / casual portfolio signal",
    scale: "土耳其 mobile games studio；公开 info 邮箱，团队规模中等。",
    signal: "休闲相关，资本能力需验证；适合 B-tier 合作/投资测试。",
    scores: [10, 20, 16, 12, 7],
    deals: "investment; co-development; acq_asset",
    dealText: "战略合作；少数投资；团队/资产讨论",
    entry: "Leadership；business development",
    contactUrl: "https://biggergames.com/",
    email: "info@biggergames.com",
    emailNote: "官网公开 info@biggergames.com。",
    angle: "用 casual audience 和 US-tested metrics 询问是否有 portfolio fit。",
    next: "B2。低成本触达。",
    confidence: "Medium",
    sources: [
      "https://biggergames.com/",
      "https://www.linkedin.com/company/bigger-games/",
      "https://www.crunchbase.com/organization/bigger-games"
    ]
  },
  {
    name: "Beach Bum / Voodoo Israel",
    country: "Israel / France",
    region: "Israel",
    website: "https://www.bbumgames.com/",
    type: "Voodoo-owned casual board/card mobile studio",
    works: "Lord of the Board, Spades Royale, Gin Rummy Stars, Domino Go",
    scale: "Voodoo 2021 年收购 Beach Bum；TechCrunch 称 Beach Bum 当时约 150 人并有数千万美元收入。",
    signal: "IAP、社交、evergreen casual 经验强；需要走 Voodoo/Beach Bum 路线。",
    scores: [12, 17, 16, 12, 5],
    deals: "co-development; publishing_mg; acq_asset",
    dealText: "Voodoo 路线合作/发行；共研；资产讨论",
    entry: "Voodoo corporate/publishing；Beach Bum leadership",
    contactUrl: "https://www.bbumgames.com/about-us/",
    email: noEmail,
    emailNote: "未找到公开公司级 BD 邮箱；建议走 Voodoo/LinkedIn。",
    angle: "如果项目社交/evergreen 玩法较强，可与其 board/card IAP 经验建立类比。",
    next: "B2。作为 Israel casual M&A map 补充。",
    confidence: "Medium",
    sources: [
      "https://www.bbumgames.com/about-us/",
      "https://techcrunch.com/2021/09/30/mobile-gaming-company-voodoo-acquires-beach-bum/",
      "https://www.gamespress.com/es/Voodoo-acquires-mobile-board-and-card-games-leader-Beach-Bum-a-major-s"
    ]
  },
  {
    name: "Naphora Games Group",
    country: "Saudi Arabia",
    region: "Saudi / GCC",
    website: "https://www.naphora.com/",
    type: "Saudi mobile games studio / game label / academy signal",
    works: "Shotball, Afrsho, NA4A",
    scale: "PocketGamer 2025 MENA Top 30 口径约 70 人，并称其以 game label 模式提供资金、设备和战略支持。",
    signal: "Saudi ecosystem 和 game label 相关，买方能力未充分公开；适合 networking/转介/轻量合作。",
    scores: [16, 18, 14, 14, 6],
    deals: "investment; co-development; publishing_mg",
    dealText: "Saudi game label；轻量投资；共研；本地服务/发行",
    entry: "Leadership / game label；founders",
    contactUrl: "https://www.naphora.com/",
    email: noEmail,
    emailNote: "官网有个人/招聘邮箱；不作为公司级 BD 主入口。",
    angle: "可把项目作为外部 mature mobile title，请其判断是否适合 Saudi label/support network。",
    next: "B2。优先用于生态引荐。",
    confidence: "Medium",
    sources: [
      "https://www.naphora.com/",
      "https://www.pocketgamer.biz/the-top-30-mena-game-makers-of-2025/",
      "https://www.grouvee.com/games/company/51478-naphora-games-group/"
    ]
  },
  {
    name: "The Games Fund",
    country: "UAE / Global",
    region: "Regional investor",
    website: "https://gamesfund.vc/",
    type: "games-focused venture fund with MENA relevance",
    works: "Hypemasters, Game Garden, Red Rover, other global games portfolio",
    scale: "games-focused VC；MENA/Abu Dhabi connection and portfolio signals。",
    signal: "偏早期 VC，不直接发行；若需要游戏专项投资和买方转介，可纳入融资线。",
    scores: [22, 12, 8, 13, 7],
    deals: "investment",
    dealText: "股权投资；桥接融资；发行/买方转介",
    entry: "Investment team；portfolio warm intro",
    contactUrl: "https://gamesfund.vc/",
    email: noEmail,
    emailNote: "未找到公开公司级 pitch 邮箱；使用官网/LinkedIn。",
    angle: "投资人版：验证数据、资金缺口、下一阶段 KPI 里程碑和可退出路径。",
    next: "B2。融资并行线，不替代发行商。",
    confidence: "Medium",
    sources: [
      "https://gamesfund.vc/",
      "https://gamesfund.vc/",
      "https://www.pocketgamer.biz/games-majlis-unites-experts-to-transform-middle-east-mobile-games-industry/"
    ]
  },
  {
    name: "Manga Productions",
    country: "Saudi Arabia",
    region: "Saudi / GCC",
    website: "https://manga.com.sa/",
    type: "Misk Foundation subsidiary focused on anime, games, comics and IP",
    works: "Future's Folktales games, UFO Robot Grendizer MENA publishing/distribution, Ghoul's Cave",
    scale: "Misk 体系；官方称支持 Saudi/Arab startups and talents in comics, animation and video games。",
    signal: "不是传统 mobile F2P 买方，但 Saudi IP/creative sector 资源强。",
    scores: [12, 13, 14, 13, 7],
    deals: "co-development; publishing_mg; investment",
    dealText: "IP/内容合作；MENA 发行；共研；生态引荐",
    entry: "Business development；Misk/Manga leadership",
    contactUrl: "https://manga.com.sa/",
    email: noEmail,
    emailNote: "未找到公开公司级游戏 BD 邮箱；使用官网/LinkedIn。",
    angle: "除非游戏有 Arab culture/IP 改造空间，否则不作为首轮资金买方。",
    next: "C1/B2。适合后续 Saudi strategic ecosystem outreach。",
    confidence: "Medium",
    sources: [
      "https://manga.com.sa/about-us/",
      "https://manga.com.sa/news/manga-productions-signs-agreement-with-nine66-to-publish-futures-folktales-hopper-quest-game-based-on-saudi-anime-series/",
      "https://www.zawya.com/en/press-release/companies-news/manga-productions-signs-an-agreement-with-french-company-microids-e2bt0uq4"
    ]
  },
  {
    name: "Papaya Gaming",
    country: "Israel",
    region: "Israel",
    website: "https://www.papayagaming.com/",
    type: "mobile skill/casual games company",
    works: "Bingo Cash, Solitaire Cash, Bubble Cash",
    scale: "大型 skill/casual mobile company；投放、竞技和变现能力强。",
    signal: "移动投放和休闲用户能力强，但 business model 与 Family Island-like 偏离。",
    scores: [9, 18, 18, 11, 6],
    deals: "investment; co-development",
    dealText: "产品/UA 交流；轻量投资；共研",
    entry: "Leadership；business development",
    contactUrl: "https://www.papayagaming.com/",
    email: noEmail,
    emailNote: "未找到公开公司级邮箱；使用官方联系入口。",
    angle: "只有在想强调 UA/retention/skill-like competition 时触达。",
    next: "C1/B2。低于 Playtika/Moon/Candivore。",
    confidence: "Medium",
    sources: [
      "https://www.papayagaming.com/",
      "https://www.papayagaming.com/",
      "https://www.linkedin.com/company/papaya-gaming"
    ]
  },
  {
    name: "Loop Games",
    country: "Turkey",
    region: "Turkey",
    website: "https://loopgames.net/",
    type: "mobile casual/puzzle studio",
    works: "Match 3D, Zen Match, casual puzzle titles",
    scale: "中型 mobile casual studio；益智和休闲用户基础。",
    signal: "休闲相关，投资/收购能力需验证；适合作为土耳其 mobile casual 生态补充。",
    scores: [8, 20, 15, 11, 6],
    deals: "co-development; investment; publishing_mg",
    dealText: "共研；轻量投资；产品交流；发行测试",
    entry: "Leadership；business development",
    contactUrl: "https://loopgames.net/",
    email: noEmail,
    emailNote: "未找到公开公司级邮箱；使用官方联系入口。",
    angle: "用休闲用户和测试数据做低摩擦触达。",
    next: "C1/B2。低优先但可批量邮件。",
    confidence: "Medium",
    sources: [
      "https://loopgames.net/",
      "https://loopgames.net/",
      "https://www.linkedin.com/company/loop-games/"
    ]
  }
];
